### ISSUE TITLE
nginx appears to be missing on Rpi 4 install 

### ISSUE THREAD

**Issue by johnster000** [didiatworkz/screenly-ose-monitoring-addon#5]
TASK [monitor-output : Reload service nginx] ************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service nginx: host"}

When installing the add-on, nginx is not found. Not sure if screenly still uses nginx in new releases, or if im supposed to install and setup nginx manually before installing the add-on

**Comment by didiatworkz** [comment]
Hello @johnster000,
which ScreenlyOSE branch do you use?

Best
didiatworkz

**Comment by johnster000** [comment]
v0.18.3 Sprint 10.1 release master branch installed on top of Raspbian lite buster

**Comment by johnster000** [comment]
After doing some digging, it looks like Screenly is using their own docker container to run nginx found at screenly/srly-ose-nginx:latest. nginx.conf file looks to be located at ~/screenly/docker/nginx/nginx.conf

**Comment by didiatworkz** [comment]
Hey @johnster000 ,

yeah, this is why I ask... And yes... fix one repo the next one is waiting 😄 
I set up a new installation.
If you want, you can test the add-on here: 
```bash
bash <(curl -sL https://raw.githubusercontent.com/didiatworkz/screenly-ose-monitoring-addon/v3.2/install.sh)
```
I can't test it fully any more for today - So be careful it's experimental! - When I have tomorrow my deployment system I will check everything, but on my Pi4 it looks fine currently.

Best
didiatworkz

**Comment by johnster000** [comment]
@didiatworkz After a fresh install of screenly, and trying to run the install.sh for 3.2 that you provided, there's an error on monitor-output task where its trying to install the requirements in the virtualenv, specifically flask==2.0.2. because ansible seems to be using python 2.7, flask 2.0.2 does not support py2.7

I really appreciate the work you have put into this whole system and I really hope I'm not being a bother with this issue

**Comment by didiatworkz** [comment]
Hello @didiatworkz 

I can agree to this issue - Changed something in the script and on my test devices everything work smooth.
You can test it with the same command as before.
Let me know what happened.

Best
didiatworkz

**Comment by johnster000** [comment]
@didiatworkz AMAZING! it worked perfectly! monitor output and device info both running flawlessly! 

Thank you so much for working away at this and solving the issue so quickly!
