### ISSUE TITLE
RPi4 Error On Monitoring

### ISSUE THREAD

**Issue by ItzBelligerent** [didiatworkz/screenly-ose-monitoring-addon#6]
Getting a localhost could not be changed and a "destination directory /etc/nginx/sites-enabled does not exist" error when attempting to install Add-On. This is on a system running Buster.

**Comment by ItzBelligerent** [comment]
TASK [monitor-output : Reload service nginx] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service nginx: host"}

**Comment by ItzBelligerent** [comment]
When attempting to use the fix provided in the other issue report, this is the error I get: fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/home/pi/soma/monitor-output/monoutenv/bin/pip2", "install", "-r", "/home/pi/soma/monitor-output/requirements.txt"], "msg": "stdout: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple\n\n:stderr: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.\nWARNING: The directory '/home/pi/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.\nERROR: Could not find a version that satisfies the requirement flask==2.0.2 (from -r /home/pi/soma/monitor-output/requirements.txt (line 1)) (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.10, 0.10.1, 0.11, 0.11.1, 0.12, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4)\nERROR: No matching distribution found for flask==2.0.2 (from -r /home/pi/soma/monitor-output/requirements.txt (line 1))\n"}

**Comment by andre2308** [comment]
Hi,
i have the same error.
I'am useing Screenly Developer Branch (Master) with a RPi 4

**Comment by didiatworkz** [comment]
Solved in V3.2 - Please try to install again and let me know about it
