### ISSUE TITLE
error :-(

### ISSUE THREAD

**Issue by ismailakincom** [didiatworkz/screenly-ose-monitoring-addon#8]
Error : fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'libpng12-dev' is available"}

I tried everything you said again but where am I going wrong?

<img width="1709" alt="Screenshot at Jan 24 16-07-21" src="https://user-images.githubusercontent.com/6472427/214300326-89a9e2c5-134e-45d5-9881-7be054cab509.png">

**Comment by didiatworkz** [comment]
Hello @ismailakincom 

Which distro do use?
64bit or 32bit?

Best

**Comment by didiatworkz** [comment]
Solved in V3.2 - Please try to install again and let me know about it
